# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/connection.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/connection.proto\"\\\n\x0e\x43onnectionInit\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0c\x63lientPubKey\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x04 \x01(\t\"{\n\x0e\x43onnectionResp\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0cserverPubKey\x18\x02 \x01(\t\x12\x12\n\nportNumber\x18\x03 \x01(\x05\x12\x14\n\x0cserverIPAddr\x18\x04 \x01(\t\x12\x1a\n\x12\x63\x65rtificateFileCrt\x18\x05 \x01(\x0c\x32K\n\x12\x43reateWGConnection\x12\x35\n\x0fStartConnection\x12\x0f.ConnectionInit\x1a\x0f.ConnectionResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTIONINIT']._serialized_start=27
  _globals['_CONNECTIONINIT']._serialized_end=119
  _globals['_CONNECTIONRESP']._serialized_start=121
  _globals['_CONNECTIONRESP']._serialized_end=244
  _globals['_CREATEWGCONNECTION']._serialized_start=246
  _globals['_CREATEWGCONNECTION']._serialized_end=321
# @@protoc_insertion_point(module_scope)
