// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: connection.proto

#include "connection.pb.h"
#include "connection.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* CreateWGConnection_method_names[] = {
  "/CreateWGConnection/StartConnection",
};

std::unique_ptr< CreateWGConnection::Stub> CreateWGConnection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CreateWGConnection::Stub> stub(new CreateWGConnection::Stub(channel));
  return stub;
}

CreateWGConnection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_StartConnection_(CreateWGConnection_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CreateWGConnection::Stub::StartConnection(::grpc::ClientContext* context, const ::ConnectionInit& request, ::ConnectionResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartConnection_, context, request, response);
}

void CreateWGConnection::Stub::experimental_async::StartConnection(::grpc::ClientContext* context, const ::ConnectionInit* request, ::ConnectionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartConnection_, context, request, response, std::move(f));
}

void CreateWGConnection::Stub::experimental_async::StartConnection(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConnectionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartConnection_, context, request, response, std::move(f));
}

void CreateWGConnection::Stub::experimental_async::StartConnection(::grpc::ClientContext* context, const ::ConnectionInit* request, ::ConnectionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartConnection_, context, request, response, reactor);
}

void CreateWGConnection::Stub::experimental_async::StartConnection(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConnectionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartConnection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ConnectionResp>* CreateWGConnection::Stub::AsyncStartConnectionRaw(::grpc::ClientContext* context, const ::ConnectionInit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::ConnectionResp>::Create(channel_.get(), cq, rpcmethod_StartConnection_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ConnectionResp>* CreateWGConnection::Stub::PrepareAsyncStartConnectionRaw(::grpc::ClientContext* context, const ::ConnectionInit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::ConnectionResp>::Create(channel_.get(), cq, rpcmethod_StartConnection_, context, request, false);
}

CreateWGConnection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CreateWGConnection_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CreateWGConnection::Service, ::ConnectionInit, ::ConnectionResp>(
          [](CreateWGConnection::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::ConnectionInit* req,
             ::ConnectionResp* resp) {
               return service->StartConnection(ctx, req, resp);
             }, this)));
}

CreateWGConnection::Service::~Service() {
}

::grpc::Status CreateWGConnection::Service::StartConnection(::grpc::ServerContext* context, const ::ConnectionInit* request, ::ConnectionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


