# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import connection_pb2 as protos_dot_connection__pb2


class CreateWGConnectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartConnection = channel.unary_unary(
                '/CreateWGConnection/StartConnection',
                request_serializer=protos_dot_connection__pb2.ConnectionInit.SerializeToString,
                response_deserializer=protos_dot_connection__pb2.ConnectionResp.FromString,
                )


class CreateWGConnectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartConnection(self, request, context):
        """creates the initial connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateWGConnectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartConnection,
                    request_deserializer=protos_dot_connection__pb2.ConnectionInit.FromString,
                    response_serializer=protos_dot_connection__pb2.ConnectionResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CreateWGConnection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreateWGConnection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CreateWGConnection/StartConnection',
            protos_dot_connection__pb2.ConnectionInit.SerializeToString,
            protos_dot_connection__pb2.ConnectionResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
