# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import image_classification_pb2 as protos_dot_image__classification__pb2


class ClassifyImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartClassification = channel.unary_unary(
                '/ClassifyImage/StartClassification',
                request_serializer=protos_dot_image__classification__pb2.ImageMessage.SerializeToString,
                response_deserializer=protos_dot_image__classification__pb2.ImageResponse.FromString,
                )


class ClassifyImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartClassification(self, request, context):
        """creates the initial connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifyImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartClassification': grpc.unary_unary_rpc_method_handler(
                    servicer.StartClassification,
                    request_deserializer=protos_dot_image__classification__pb2.ImageMessage.FromString,
                    response_serializer=protos_dot_image__classification__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassifyImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassifyImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartClassification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassifyImage/StartClassification',
            protos_dot_image__classification__pb2.ImageMessage.SerializeToString,
            protos_dot_image__classification__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
