# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/text_binary_classification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'protos/text_binary_classification.proto\"\x1f\n\rPromptMessage\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"%\n\x0ePromptResponse\x12\x13\n\x0b\x64oesViolate\x18\x01 \x01(\x08\x32L\n\x0c\x43lassifyText\x12<\n\x17StartTextClassification\x12\x0e.PromptMessage\x1a\x0f.PromptResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.text_binary_classification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROMPTMESSAGE']._serialized_start=43
  _globals['_PROMPTMESSAGE']._serialized_end=74
  _globals['_PROMPTRESPONSE']._serialized_start=76
  _globals['_PROMPTRESPONSE']._serialized_end=113
  _globals['_CLASSIFYTEXT']._serialized_start=115
  _globals['_CLASSIFYTEXT']._serialized_end=191
# @@protoc_insertion_point(module_scope)
