// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: text_binary_classification.proto
#ifndef GRPC_text_5fbinary_5fclassification_2eproto__INCLUDED
#define GRPC_text_5fbinary_5fclassification_2eproto__INCLUDED

#include "text_binary_classification.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// Allows a user to send a yes or no question to an LLM and 
// recieve a response back
class ClassifyText final {
 public:
  static constexpr char const* service_full_name() {
    return "ClassifyText";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // creates the initial connection
    virtual ::grpc::Status StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage& request, ::PromptResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromptResponse>> AsyncStartTextClassification(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromptResponse>>(AsyncStartTextClassificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromptResponse>> PrepareAsyncStartTextClassification(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromptResponse>>(PrepareAsyncStartTextClassificationRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // creates the initial connection
      virtual void StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PromptResponse>* AsyncStartTextClassificationRaw(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PromptResponse>* PrepareAsyncStartTextClassificationRaw(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage& request, ::PromptResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromptResponse>> AsyncStartTextClassification(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromptResponse>>(AsyncStartTextClassificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromptResponse>> PrepareAsyncStartTextClassification(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromptResponse>>(PrepareAsyncStartTextClassificationRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, std::function<void(::grpc::Status)>) override;
      void StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PromptResponse>* AsyncStartTextClassificationRaw(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PromptResponse>* PrepareAsyncStartTextClassificationRaw(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartTextClassification_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // creates the initial connection
    virtual ::grpc::Status StartTextClassification(::grpc::ServerContext* context, const ::PromptMessage* request, ::PromptResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartTextClassification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartTextClassification() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartTextClassification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTextClassification(::grpc::ServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartTextClassification(::grpc::ServerContext* context, ::PromptMessage* request, ::grpc::ServerAsyncResponseWriter< ::PromptResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartTextClassification<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StartTextClassification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StartTextClassification() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::PromptMessage, ::PromptResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::PromptMessage* request, ::PromptResponse* response) { return this->StartTextClassification(context, request, response); }));}
    void SetMessageAllocatorFor_StartTextClassification(
        ::grpc::experimental::MessageAllocator< ::PromptMessage, ::PromptResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::PromptMessage, ::PromptResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_StartTextClassification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTextClassification(::grpc::ServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StartTextClassification(
      ::grpc::CallbackServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StartTextClassification(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_StartTextClassification<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_StartTextClassification<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartTextClassification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartTextClassification() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartTextClassification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTextClassification(::grpc::ServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartTextClassification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartTextClassification() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartTextClassification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTextClassification(::grpc::ServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartTextClassification(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StartTextClassification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StartTextClassification() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartTextClassification(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_StartTextClassification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTextClassification(::grpc::ServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StartTextClassification(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StartTextClassification(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartTextClassification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartTextClassification() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::PromptMessage, ::PromptResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::PromptMessage, ::PromptResponse>* streamer) {
                       return this->StreamedStartTextClassification(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartTextClassification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartTextClassification(::grpc::ServerContext* /*context*/, const ::PromptMessage* /*request*/, ::PromptResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartTextClassification(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PromptMessage,::PromptResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartTextClassification<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartTextClassification<Service > StreamedService;
};


#endif  // GRPC_text_5fbinary_5fclassification_2eproto__INCLUDED
