// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: text_binary_classification.proto

#include "text_binary_classification.pb.h"
#include "text_binary_classification.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* ClassifyText_method_names[] = {
  "/ClassifyText/StartTextClassification",
};

std::unique_ptr< ClassifyText::Stub> ClassifyText::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ClassifyText::Stub> stub(new ClassifyText::Stub(channel));
  return stub;
}

ClassifyText::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_StartTextClassification_(ClassifyText_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ClassifyText::Stub::StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage& request, ::PromptResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartTextClassification_, context, request, response);
}

void ClassifyText::Stub::experimental_async::StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartTextClassification_, context, request, response, std::move(f));
}

void ClassifyText::Stub::experimental_async::StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartTextClassification_, context, request, response, std::move(f));
}

void ClassifyText::Stub::experimental_async::StartTextClassification(::grpc::ClientContext* context, const ::PromptMessage* request, ::PromptResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartTextClassification_, context, request, response, reactor);
}

void ClassifyText::Stub::experimental_async::StartTextClassification(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PromptResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartTextClassification_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::PromptResponse>* ClassifyText::Stub::AsyncStartTextClassificationRaw(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::PromptResponse>::Create(channel_.get(), cq, rpcmethod_StartTextClassification_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::PromptResponse>* ClassifyText::Stub::PrepareAsyncStartTextClassificationRaw(::grpc::ClientContext* context, const ::PromptMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::PromptResponse>::Create(channel_.get(), cq, rpcmethod_StartTextClassification_, context, request, false);
}

ClassifyText::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClassifyText_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClassifyText::Service, ::PromptMessage, ::PromptResponse>(
          [](ClassifyText::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::PromptMessage* req,
             ::PromptResponse* resp) {
               return service->StartTextClassification(ctx, req, resp);
             }, this)));
}

ClassifyText::Service::~Service() {
}

::grpc::Status ClassifyText::Service::StartTextClassification(::grpc::ServerContext* context, const ::PromptMessage* request, ::PromptResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


