# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import text_binary_classification_pb2 as protos_dot_text__binary__classification__pb2


class ClassifyTextStub(object):
    """Allows a user to send a yes or no question to an LLM and 
    recieve a response back
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTextClassification = channel.unary_unary(
                '/ClassifyText/StartTextClassification',
                request_serializer=protos_dot_text__binary__classification__pb2.PromptMessage.SerializeToString,
                response_deserializer=protos_dot_text__binary__classification__pb2.PromptResponse.FromString,
                )


class ClassifyTextServicer(object):
    """Allows a user to send a yes or no question to an LLM and 
    recieve a response back
    """

    def StartTextClassification(self, request, context):
        """creates the initial connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifyTextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTextClassification': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTextClassification,
                    request_deserializer=protos_dot_text__binary__classification__pb2.PromptMessage.FromString,
                    response_serializer=protos_dot_text__binary__classification__pb2.PromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassifyText', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassifyText(object):
    """Allows a user to send a yes or no question to an LLM and 
    recieve a response back
    """

    @staticmethod
    def StartTextClassification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassifyText/StartTextClassification',
            protos_dot_text__binary__classification__pb2.PromptMessage.SerializeToString,
            protos_dot_text__binary__classification__pb2.PromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
