# Use the official Ubuntu as the base image
FROM ubuntu:latest

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
ENV NETWORK_MODE=host

COPY modify_response.py .
COPY redis-config.ini .
COPY terminal_run_wireguard.py .
COPY ./keys /etc/keys
COPY RecieveConnections.py .
COPY protos/ protos/
COPY .mitmproxy/ .mitmproxy/
COPY ./fill.png /fill.png

COPY run_wireguard.py .
COPY wireguard_server_impl.py .
COPY wireguard.conf .
COPY cert.pem .

# Update package lists and install necessary dependencies
RUN apt update -y && apt upgrade -y && \
    apt install -y python3-pip
RUN apt install -y apt-utils wget unzip git wireguard python3.10-venv vim netcat

RUN mkdir venv && python3 -m venv venv
ENV PATH="/venv/bin:$PATH"
# Install TensorFlow using pip
RUN pip3 install protobuf==3.20.* tensorflow==2.12.1
RUN pip3 install nsfw-detector redis grpcio # mitmproxy

# build "custom" version of mitmproxy
RUN git clone https://github.com/thansen0/mitmproxy-pubkey.git
RUN cd mitmproxy-pubkey && pip3 install .

#RUN wget https://github.com/GantMan/nsfw_model/releases/download/1.1.0/nsfw_mobilenet_v2_140_224.zip && unzip nsfw_mobilenet_v2_140_224.zip
COPY nsfw_mobilenet_v2_140_224.zip .
RUN unzip nsfw_mobilenet_v2_140_224.zip

# Clean up the package cache to reduce the image size
# RUN apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# Start a shell when the container runs
#CMD ["/bin/bash"]
#ENTRYPOINT ["mitmdump", "-s", "modify_response.py", "--proxyauth", "username:password", "--set", "block_global=false"]
#ENTRYPOINT ["mitmdump", "-s", "modify_response.py", "--mode", "wireguard"]
#ENTRYPOINT ["python3", "run_wireguard.py"]

# production arguments
ENTRYPOINT ["python3", "terminal_run_wireguard.py"]
