# Use the official Ubuntu as the base image
FROM ubuntu:latest

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
ENV NETWORK_MODE=host

COPY modify_response.py .
COPY redis-config.ini .
COPY run_wireguard.py .
# add copy for certificate
COPY ./keys/cert.key cert.pem

# Update package lists and install necessary dependencies
RUN apt update -y && apt upgrade -y && \
    apt install -y python3-pip
RUN apt install -y apt-utils wget unzip git wireguard

# Install TensorFlow using pip
RUN pip3 install protobuf==3.20.*
RUN pip3 install tensorflow==2.12.1
RUN pip3 install nsfw-detector mitmproxy mitmproxy-wireguard redis grpcio

#RUN wget https://github.com/GantMan/nsfw_model/releases/download/1.1.0/nsfw_mobilenet_v2_140_224.zip && unzip nsfw_mobilenet_v2_140_224.zip
COPY nsfw_mobilenet_v2_140_224.zip .
RUN unzip nsfw_mobilenet_v2_140_224.zip

# Clean up the package cache to reduce the image size
# RUN apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# Start a shell when the container runs
CMD ["/bin/bash"] # for testing, you have to run wireguard and mitmproxy on your own this way
#ENTRYPOINT ["mitmdump", "-s", "modify_response.py", "--proxyauth", "username:password", "--set", "block_global=false"]
#ENTRYPOINT ["mitmdump", "-s", "modify_response.py", "--mode", "wireguard"]
#ENTRYPOINT ["python", "run_wireguard.py"]
#ENTRYPOINT ["python", "terminal_run_wireguard.py"] # production arguments
